syntax on
set nowrap
set encoding=utf-8
set number
set smartindent
filetype plugin indent on
set tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
colorscheme desert

map <F5> :update<CR>:make<CR>
imap <F5> <ESC>:update<CR>:make<CR>
